### ISSUE TITLE
Sometimes questions only have 1 answer to choose from

### ISSUE THREAD

**Issue by farfromunique** [LemonAndroid/qanda-wikipedia#23]
![image](https://user-images.githubusercontent.com/4977323/42338601-26cddec4-803f-11e8-9912-4c1c911e8a2c.png)

**Comment by MangoSmoothie101010** [comment]
Hey!

This issue should occur a lot less after https://github.com/MangoSmoothie101010/qanda-wikipedia/issues/20 and more importantly the fix that is dependent on it is implemented.

It will be completely eliminated when choices are fetched using word vector similarity instead of 1 word category tag matching.

**Comment by LemonAndroid** [comment]
resolved now, thanks again for reporting @farfromunique
